name: verterok-testsnap
version: 2018-07-20-01
summary: The crappiest snap in the universe.
confinement: strict
grade: stable
description: This crappy snap just shows some emojis.

architectures:
  - amd64

apps:
  crap:
    command: echo "💩 hello 💩 how about more emojis 🍌"

parts:
  empty:
    plugin: nil

